#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

# A set of useful config settings to facilitate troubleshooting
pcap:
  mac_enable: true
  mac_type: dlt
  rlc_enable: false
  rlc_rb_type: srb
  ngap_enable: false

log:
  all_level: warning
  config_level: debug

metrics:
  enable_log: true
  layers:
    enable_ru: true
    enable_sched: true
